### ISSUE TITLE
[Issues in config files] How can I get AE/scripts/configs/{module}.yaml for other apps?

### ISSUE THREAD

**Issue by taehun-kim00** [Cloud-and-Distributed-Systems/Erms#12]
Hi. I'm trying to testing Erms with social-network.
But, there are some problems.

![Image](https://github.com/user-attachments/assets/4d17c238-088c-4840-b4bb-040542190e29)

I got some errors when executing `bash AE/scripts/latency-target-computation.sh --app social-network`

I think the reason is that `AE/scripts/configs/latency-target-computation.yaml` is for the hotel-reservation.

How can I get different version of the config files of each modules?

Thanks!

**Comment by Nick-LCY** [comment]
Hi,

I checked the code and find out that there might be a typo in code.

https://github.com/Cloud-and-Distributed-Systems/Erms/blob/debd2fa0b8e8aae516b9fb63238aae920b46fa76/AE/scripts/latency-target-computation.py#L24

Firstly, could you please change this line to the following, and test if it works with `HotelReservation` application: 
```python
    default="AE/scripts/configs/latency-target-computation.yaml"
```


If that works, you may use the following config file for `SocialNetwork` application

```yaml
services:
- ComposePost

# If you use the data we provided, I think the following configs are okay.
# But if you use your own data, you need to change interferences to match yours.
interferences:
  # Units: core
  cpu: 0.4
  # Units: MiB
  mem: 800

# The same with interferences part👆
# Units: requests per min
workloads:
  ComposePost: 100

# You should check profiling data and set a reasonable SLA
# Units: ms
slas:
  ComposePost: 300
```
