### ISSUE TITLE
[Nginx MountVolume Failed] Some configuration files are missing

### ISSUE THREAD

**Issue by caohch-1** [Cloud-and-Distributed-Systems/Erms#5]
Trying to deploy media-microsvc and one of the pods stays in `ContainerCreating`.
Following is the detail infomation:
```bash
(base) caohch1@caohch1-OptiPlex-7090:~/Desktop$ kubectl describe pod nginx-web-server-7fbfff44cb-frhzh -n media-microsvc
Name:             nginx-web-server-7fbfff44cb-frhzh
Namespace:        media-microsvc
...
Containers:
  nginx-web-server:
    ...
    Mounts:
      /gen-lua from gen-lua (rw)
      /usr/local/openresty/nginx/conf/nginx.conf from nginx-conf (rw)
      /usr/local/openresty/nginx/jaeger-config.json from jaeger-config-json (rw)
      /usr/local/openresty/nginx/lua-scripts from lua-scripts (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9d6j6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  lua-scripts:
    Type:          HostPath (bare host directory volume)
    Path:          /root/media/lua-scripts-k8s
    HostPathType:  DirectoryOrCreate
  nginx-conf:
    Type:          HostPath (bare host directory volume)
    Path:          /root/media/nginx-k8s.conf
    HostPathType:  File
  jaeger-config-json:
    Type:          HostPath (bare host directory volume)
    Path:          /root/media/jaeger-config.json
    HostPathType:  File
  gen-lua:
    Type:          HostPath (bare host directory volume)
    Path:          /root/media/gen-lua
    HostPathType:  DirectoryOrCreate
  kube-api-access-9d6j6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
# Pay attention here
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    49s                default-scheduler  Successfully assigned media-microsvc/nginx-web-server-7fbfff44cb-frhzh to minikube-m03
  Warning  FailedMount  17s (x7 over 49s)  kubelet            MountVolume.SetUp failed for volume "jaeger-config-json" : hostPath type check failed: /root/media/jaeger-config.json is not a file
  Warning  FailedMount  17s (x7 over 49s)  kubelet            MountVolume.SetUp failed for volume "nginx-conf" : hostPath type check failed: /root/media/nginx-k8s.conf is not a file
```

Thus, I check the file `nginx-web-server_Deployment.yaml` and find following fields:
```yaml
volumes:
      - hostPath:
          path: /root/media/lua-scripts-k8s
          type: DirectoryOrCreate
        name: lua-scripts
      - hostPath:
          path: /root/media/nginx-k8s.conf
          type: File
        name: nginx-conf
      - hostPath:
          path: /root/media/jaeger-config.json
          type: File
        name: jaeger-config-json
      - hostPath:
          path: /root/media/gen-lua
          type: DirectoryOrCreate
        name: gen-lua
```
It seems that some files are stored in your `/root` dir instead of `/erms`. Did you forget to upload these files or dirs? Or where can I download these files? Or what rules should I follow to write these files?
Similar problems while deploying `social-network` in two `Deployment` as follows:
```yaml
# media-frontend.yaml
    spec:
      containers:
      - name: media-frontend
        image: yg397/media-frontend:xenial
        ports: 
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/local/openresty/nginx/lua-scripts
          name: lua-scripts
        - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          name: nginx-conf
      restartPolicy: Always
      volumes:
      - name: lua-scripts
        hostPath: 
          path: /root/firm/benchmarks/1-social-network/media-frontend/lua-scripts-k8s
          type: DirectoryOrCreate
      - name: nginx-conf
        hostPath: 
          path: /root/firm/benchmarks/1-social-network/media-frontend/conf/nginx-k8s.conf
          type: File


# nginx-thrift.yaml
spec:
      containers:
      - name: nginx-thrift
        image: yg397/openresty-thrift:xenial
        ports: 
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/local/openresty/nginx/lua-scripts
          name: lua-scripts
        - mountPath: /usr/local/openresty/nginx/pages
          name: pages
        - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          name: nginx-conf
        - mountPath: /usr/local/openresty/nginx/jaeger-config.json
          name: jaeger-config-json
        - mountPath: /gen-lua
          name: gen-lua
      restartPolicy: Always
      volumes:
      - name: lua-scripts
        hostPath: 
          path: /root/firm/benchmarks/1-social-network/nginx-web-server/lua-scripts-k8s
          type: DirectoryOrCreate
      - name: pages
        hostPath: 
          path: /root/firm/benchmarks/1-social-network/nginx-web-server/pages
          type: DirectoryOrCreate
      - name: nginx-conf
        hostPath: 
          path: /root/firm/benchmarks/1-social-network/nginx-web-server/conf/nginx-k8s.conf
          type: File
      - name: jaeger-config-json
        hostPath: 
          path: /root/firm/benchmarks/1-social-network/nginx-web-server/jaeger-config.json
          type: File
      - name: gen-lua
        hostPath: 
          path: /root/firm/benchmarks/1-social-network/gen-lua
          type: DirectoryOrCreate
```
